services:
  - type: web
    name: pinad-python-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: GOOGLE_API_KEY
        value: AIzaSyAG0gM9rUHowL14Aig5KrMtfdeSxnkYQik
      - key: GOOGLE_CLIENT_ID
        value: 531174220363-3aeog10kkqkmbbgo21nsinf110u3qcin.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: YOUR_CLIENT_SECRET
      - key: GMAIL_NOTIFICATION_EMAIL
        value: contador@ejemplo.com
      - key: DRIVE_BACKUP_FOLDER
        value: PINAD_Documentos
      - key: SHEETS_REPORT_FOLDER
        value: PINAD_Reportes
      - key: CALENDAR_REMINDER_CALENDAR
        value: PINAD_Recordatorios
